from pathlib import Path
import json,html,hashlib,re
R=Path(__file__).resolve().parents[1];D=R/'dist';pages=json.loads((R/'content/academy.json').read_text());by={p['path']:p for p in pages};team=json.loads((R/'content/team.json').read_text())
H=html.escape
def asset(u,thumb=False):
 path='/assets/academy/'+hashlib.sha256(u.encode()).hexdigest()[:16]+('-thumb' if thumb else '')+'.webp'
 return path if (D/path.lstrip('/')).is_file() else u
def img(u,alt,cls='',lazy=True):return f'<img src="{asset(u)}" alt="{H(alt)}" class="{cls}" loading="{"lazy" if lazy else "eager"}" decoding="async">'
def url(path):return '/'+path
free='enroll-for-a-free-trial-class-today/'
def header(active):
 nav=''.join(f'<a href="{href}"'+(' aria-current="page"' if key==active else '')+f'>{title}</a>' for key,title,href in [('home','Home','/'),('about','About','/about-us/'),('events','Events','/events/'),('shop','Shop','/shop/'),('contact','Contact','/contact-us/')])
 return f'''<a href="#main" class="skip-link">Skip to content</a><div class="announcement">ADLY CHESS ACADEMY <span>THINK. COMPETE. GROW.</span></div><header class="header"><a class="brand" href="/" aria-label="Adly Chess Academy"><img src="/assets/cropped-cropped-Logo-1000x1000-1.png" alt="Adly Chess Academy" width="160" height="60"></a><nav id="site-nav" aria-label="Main navigation">{nav}</nav><a class="header-cta" href="/{free}">Try a free class <span aria-hidden="true">↗</span></a><button class="menu-toggle" aria-label="Toggle navigation" aria-controls="site-nav" aria-expanded="false">Menu</button></header>'''
def footer():return f'''<footer class="site-footer"><a class="footer-brand" href="/">ADLY <span>CHESS ACADEMY</span></a><div><p class="footer-label">Explore</p><ul><li><a href="/about-us/">Our story</a></li><li><a href="/about-us/our-team/">Our team</a></li><li><a href="/events/">Events</a></li><li><a href="/shop/">The collection</a></li></ul></div><div><p class="footer-label">Your next move</p><ul><li><a href="/{free}">Free trial class</a></li><li><a href="/contact-us/">Contact & branches</a></li><li><a href="https://www.facebook.com/Adly.Chess.Academy" target="_blank" rel="noopener">Facebook ↗</a></li><li><a href="https://www.instagram.com/adly.chess.academy" target="_blank" rel="noopener">Instagram ↗</a></li></ul></div><div class="footer-location"><p class="footer-label">Visit the academy</p><iframe class="footer-map" title="Adly Chess Academy — Nasr City location" src="https://maps.google.com/maps?q=Adly+Chess+Academy&z=14&t=roadmap&output=embed" width="360" height="190" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe><a class="footer-directions" href="https://maps.app.goo.gl/729Snk4tVkBTBXEx6" target="_blank" rel="noopener">Get directions <span aria-hidden="true">↗</span></a><p>37 Mohammed Youssef Moussa,<br>Nasr City, Cairo, Egypt</p><p><a href="tel:+201033172288">+20 103 317 2288</a><br><a href="mailto:info@adlychess.com">info@adlychess.com</a></p></div><div class="footer-bottom"><p>Adly Chess Academy · Think. Compete. Grow.</p><p>Photography © Adly Chess Academy and respective owners.</p></div></footer>'''
def closing():return f'''<section class="closing"><p class="eyebrow">YOUR NEXT CHAPTER STARTS HERE</p><div><h2>Make your<br>first move.</h2><p>Discover a game to grow with.<br>Join the Adly chess community.<a href="/{free}">Try a free class <span aria-hidden="true">↗</span></a></p></div></section>'''
def crumb(label,parent=None):return '<div class="breadcrumb"><a href="/">Home</a><span>/</span>'+ (f'<a href="/{parent[0]}">{H(parent[1])}</a><span>/</span>' if parent else '')+H(label)+'</div>'
def write(path,title,desc,body,active='about',cta=True):
 f=D/path/'index.html';f.parent.mkdir(parents=True,exist_ok=True)
 f.write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{H(title)} | Adly Chess Academy</title><meta name="description" content="{H(desc)}"><link rel="icon" href="/assets/cropped-cropped-Logo-1000x1000-1.png"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/academy.css"><script src="/academy.js?v=forms-1" defer></script></head><body>{header(active)}<main id="main">{body}{closing() if cta else ''}</main>{footer()}</body></html>''')
def people(items):return '<div class="people-grid">'+''.join(f'<article class="person">{img(p["image"],p["name"])}<h3>{H(p["name"])}</h3><p>{H(p["role"])}</p></article>' for p in items)+'</div>'
about=by['about-us/'];founder=team[0]
body=f'''<div class="page-shell">{crumb('Our story')}<section class="page-hero"><div><p class="eyebrow">THE ACADEMY / OUR STORY</p><h1>Great players.<br><em>Greater possibilities.</em></h1><p class="lead">A champion’s experience. A new generation’s opportunity. Discover the story behind Adly Chess Academy.</p><div class="button-row"><a class="button" href="/{free}">Try a free class <span>↗</span></a><a class="button secondary" href="/about-us/our-team/">Meet our team</a></div></div><figure class="hero-photo">{img(founder['image'],'Grandmaster Ahmed Adly, founder of Adly Chess Academy',lazy=False)}<figcaption class="photo-caption"><span>GM Ahmed Adly · Founder & CEO</span><span>World Junior Champion, 2007</span></figcaption></figure></section><div class="metric-strip"><div class="metric"><strong>2007</strong><span>World Junior Championship title</span></div><div class="metric"><strong>Every level</strong><span>From first moves to competition</span></div><div class="metric"><strong>In person + online</strong><span>A community beyond the classroom</span></div></div><section class="editorial-section editorial-grid"><div><p class="eyebrow">FROM A CHAMPION’S JOURNEY</p><h2>A better beginning<br>for the next generation.</h2></div><div class="prose"><p>After becoming World Junior Chess Champion in 2007, Ahmed Adly wanted young players to have the structured coaching and training environment he had struggled to find.</p><p>That ambition became Adly Chess Academy: a place where children can learn with dedicated coaches, follow a clear curriculum, and experience competition in a supportive community.</p><p>Today, that purpose reaches beyond the result of a game. The academy encourages thoughtful decisions, responsibility and respect alongside a lasting love of chess.</p></div></section><figure class="story-photo">{img(about['images'][0]['url'],'Adly Chess Academy participating in Sports Expo')}<figcaption>Learning, competing and connecting through chess.</figcaption></figure><div class="purpose"><article><p class="eyebrow">OUR MISSION</p><h3>Develop the player.<br>Encourage the thinker.</h3><p>Use chess to nurture critical thinking, good sportsmanship and the confidence to take on new challenges.</p></article><article><p class="eyebrow">OUR VISION</p><h3>Champions on the board.<br>Positive people beyond it.</h3><p>Build a community of capable players who bring integrity and purpose to everything they do.</p></article></div><section class="editorial-section"><p class="eyebrow">WHAT WE STAND FOR</p><h2>Values in every move.</h2><ul class="value-list">{''.join(f'<li><span>0{i+1}</span>{v}</li>' for i,v in enumerate(['Cooperation','Achievement','Empathy','Respect','Fair play']))}</ul></section><section class="team-section"><div class="section-heading"><div><p class="eyebrow">PEOPLE BEHIND THE PROGRESS</p><h2>Meet our board.</h2></div><a href="/about-us/our-team/">The full team ↗</a></div>{people(team[:4])}</section></div>'''
write('about-us','Our story','The story, purpose and people behind Adly Chess Academy.',body)
body=f'<div class="page-shell">{crumb("Our team",("about-us/","About"))}<section class="text-hero"><p class="eyebrow">THE PEOPLE BEHIND THE ACADEMY</p><h1>Experience to guide.<br><em>Passion to inspire.</em></h1><p class="lead">Meet the board, coaches and team who bring the Adly chess community to life.</p></section>'
for group in dict.fromkeys(p['group'] for p in team):body+=f'<section class="team-section"><h2>{H(group.title())}</h2>{people([p for p in team if p["group"]==group])}</section>'
write('about-us/our-team','Our team','Meet the coaches, leadership and academy team.',body+'</div>')
def field(label,kind='text',wide=False,options=None,autocomplete=None,required=True):
 attr=' required' if required else '';name='email' if label=='Email' else H(label);klass='field wide' if wide else 'field';ac=f' autocomplete="{autocomplete}"' if autocomplete else ''
 if options:control=f'<select name="{name}"{attr}><option value="">Select an option</option>'+''.join(f'<option>{H(o)}</option>' for o in options)+'</select>'
 elif kind=='textarea':control=f'<textarea name="{name}" rows="5" maxlength="2000"{attr}></textarea>'
 else:control=f'<input type="{kind}" name="{name}" maxlength="150"{ac}{attr}>'
 return f'<label class="{klass}">{H(label)}{" *" if required else ""}{control}</label>'
def form(trial=False):
 fields=field('First name',autocomplete='given-name')+field('Last name',autocomplete='family-name')+field('Email','email',autocomplete='email')+field('Phone number','tel',autocomplete='tel')
 if trial:fields+=field('Trainee’s name',wide=True)+field('Trainee’s age',options=['5–8 years','9–12 years','13–15 years'])+field('Preferred location',options=['Online','Nasr City, Cairo','Madinaty, Cairo','5th Settlement, Cairo','Maadi, Cairo','Sheraton, Cairo','Zayed, Giza','Port Said','New Damietta','Mamzar, Dubai'])+field('Chess experience',wide=True,options=['New to chess','Knows the basic rules','Has taken classes / plays well','Has played tournaments'])
 else:fields+=field('Inquiry type',wide=True,options=['General','Training sessions','Events & sponsorships','Buying products'])+field('Your message','textarea',wide=True)
 return f'''<form class="academy-form" data-type="{'trial' if trial else 'contact'}" method="POST">{fields}<input type="hidden" name="_subject" value="Adly website — {'Free trial class request' if trial else 'Contact inquiry'}"><input type="hidden" name="_template" value="table"><input class="form-honeypot" type="text" name="_honey" autocomplete="off" aria-hidden="true"><button class="button wide" type="submit">{'Request a free class' if trial else 'Send message'} <span aria-hidden="true">↗</span></button><div class="form-status wide" role="status" aria-live="polite" hidden></div><p class="form-note wide">Your details are processed by <a href="https://formsubmit.co/privacy.pdf" target="_blank" rel="noopener">FormSubmit</a> and emailed to Adly Chess Academy at info@adlychess.com. {'The academy will contact you to confirm class availability. Submitting this form does not confirm a booking.' if trial else 'The academy will use your contact details to respond to your inquiry.'}</p></form>'''

branches=[('Nasr City — Main Branch','37 Mohammed Youssef Moussa, Al Manteqah Al Oula, Nasr City, Egypt','01033117744'),('Sheraton — The Club','Sheraton Al Matar, El Nozha, Cairo, Egypt','01093677868'),('Zayed — Zayed Sports Club','Dr Ali Lotfy, First Al Sheikh Zayed, Giza, Egypt','01020106088'),('Madinaty — Golf Club','Madinaty, Second New Cairo, Cairo, Egypt','01022526222'),('5th Settlement — Royal Sporting Club','90 St, Club Land, New Cairo, Egypt','01093677868'),('Maadi — A1 Educenter','Villa 1A, 19th Street, from Victory Square, Degla Maadi, Cairo, Egypt','01010305828'),('Port Said — Porto Sporting Club','El Manasra, Port Said, Egypt','01022224561'),('New Damietta — Olympia Sports Club','Damietta El-Gadeeda City, Egypt','01205571377'),('Dubai — Chess & Culture Club','Gate 8, Street 44, Al Wuhaida Road, Community 134, Al Mamzar, Dubai, UAE','')]
maps=[a['url'] for a in by['contact-us/']['links'] if a['text']=='Location Map']
branchHTML=''.join(f'<details class="branch"><summary>{H(n)}</summary><p>{H(a)}</p><p>'+ (f'<a href="tel:+2{phone}">{phone}</a>' if phone else '<a href="mailto:info@adlychess.com">Ask about this branch</a>')+f'<a href="{maps[i]}" target="_blank" rel="noopener">Directions ↗</a></p></details>' for i,(n,a,phone) in enumerate(branches))
body=f'''<div class="page-shell">{crumb('Contact')}<section class="contact-layout"><div><p class="eyebrow">LET’S TALK CHESS</p><h1>Your next move<br><em>starts here.</em></h1><p class="intro">A question about classes, a tournament or your first chess set? Get in touch with the academy.</p><ul class="contact-details"><li><span>Call us</span><a href="tel:+201033172288">+20 103 317 2288</a></li><li><span>Email us</span><a href="mailto:info@adlychess.com">info@adlychess.com</a></li><li><span>Visit our main branch</span><a href="https://maps.app.goo.gl/729Snk4tVkBTBXEx6" target="_blank" rel="noopener">37 Mohammed Youssef Moussa,<br>Al Manteqah Al Oula, Nasr City, Cairo ↗</a></li><li><span>Opening hours</span><p>4 PM – 10 PM<br>Wednesday to Monday</p></li></ul></div><div class="form-card"><h2>Get in touch.</h2><p class="form-intro">Tell us what you have in mind. Fields marked * are required.</p>{form()}</div></section><section class="map-panel"><div><p class="eyebrow">FIND YOUR WAY TO THE BOARD</p><h2>See you<br>in Nasr City.</h2><p>Visit the academy’s main branch.<br>Call ahead to discuss the right class for you.</p><a class="button secondary" href="https://maps.app.goo.gl/729Snk4tVkBTBXEx6" target="_blank" rel="noopener">Get directions <span>↗</span></a></div><iframe title="Adly Chess Academy location map" src="https://maps.google.com/maps?q=Adly+Chess+Academy&z=14&t=roadmap&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></section><section><p class="eyebrow">CLOSER TO YOUR GAME</p><h2>Our locations.</h2><div class="branch-grid">{branchHTML}<details class="branch"><summary>Online classes</summary><p>Learn from home, wherever you are. Choose Online when requesting your free class.</p><p><a href="/{free}">Request a free class ↗</a></p></details></div></section></div>'''
write('contact-us','Contact & locations','Get in touch with Adly Chess Academy and find a nearby branch or online class.',body,'contact',False)
trialpic=by[free]['images'][0]['url']
body=f'''<div class="page-shell">{crumb('Free trial class')}<section class="page-hero trial-hero"><div><p class="eyebrow">ONE CLASS. A WORLD OF POSSIBILITIES.</p><h1>First moves.<br><em>Lasting curiosity.</em></h1><p class="lead">Give your child a chance to discover chess with a free trial class at Adly Chess Academy.</p><ul class="benefit-list"><li><span>01</span>In-person and online learning</li><li><span>02</span>Coaching for different experience levels</li><li><span>03</span>A curriculum focused on young players</li></ul>{img(trialpic,'Students and coaches at Adly Chess Academy','trial-image')}</div><div class="form-card"><h2>Let’s find your first class.</h2><p class="form-intro">A parent or guardian should complete this request. Fields marked * are required.</p>{form(True)}</div></section><section class="steps"><article><span class="step-num">01</span><h3>Share a few details.</h3><p>Tell the academy your child’s age, experience and preferred location.</p></article><article><span class="step-num">02</span><h3>Arrange your session.</h3><p>The team will help you choose a suitable class and confirm availability.</p></article><article><span class="step-num">03</span><h3>Make the first move.</h3><p>Meet a coach, explore the game and decide what comes next.</p></article></section></div>'''
write(free.strip('/'),'Free trial class','Request a free trial chess class for your child, in person or online.',body,'free',False)
# Event pages preserve the source hierarchy and every available gallery image.
names={'events/':'Events','events/adly-international-chess-festival/':'Adly International Chess Festival','events/african-youth-chess-championship-2023/':'African Youth Chess Championship 2023','events/sports-expo/':'Sports Expo','events/tournaments/':'Tournaments'}
for p in pages:
 if p.get('title'):names[p['path']]=p['title']
intros={'events/':('More than a game.','A community in motion.','Explore the festivals, championships and tournament moments that bring the Adly chess community together.'),'events/adly-international-chess-festival/':('The festival.','The shared passion.','Explore the Adly International Chess Festival archive and the moments captured across its editions.'),'events/sports-expo/':('Chess meets','a wider world.','See the academy’s appearances at Sports Expo, bringing chess to new players and new audiences.'),'events/tournaments/':('Across the board.','Around the country.','Browse tournament photographs from clubs, schools and chess communities.')}
def cards(p):
 links=[a for a in p['links'] if a['url'] and a['url'].startswith('https://adlychess.com/events/')];result=''
 for i,a in enumerate(links):
  path=a['url'].removeprefix('https://adlychess.com/');photo=p['images'][i]['url'];title=names.get(path,a['text']);child=by.get(path,{});count=len(child.get('images',[]));label='Explore events' if child.get('links') else str(count)+' photographs'
  result+=f'<a class="event-card" href="/{path}"><div class="event-card-image">{img(photo,title)}</div><div class="event-card-body"><div><p>{label}</p><h2>{H(title)}</h2></div><span class="round-arrow" aria-hidden="true">↗</span></div></a>'
 return '<div class="event-categories">'+result+'</div>'
for p in pages:
 path=p['path']
 if not path.startswith('events/'):continue
 title=names[path];parentPath='/'.join(path.strip('/').split('/')[:-1])+'/' if path!='events/' else None;parent=(parentPath,names.get(parentPath,'Events')) if parentPath else None
 if path in intros:
  line1,line2,intro=intros[path];body=f'<div class="page-shell">{crumb(title,parent)}<section class="text-hero"><p class="eyebrow">ADLY CHESS / EVENTS</p><h1>{line1}<br><em>{line2}</em></h1><p class="lead">{intro}</p></section>{cards(p)}<p class="archive-note">Explore past events and photo galleries. For upcoming dates, participation or sponsorships, <a href="/contact-us/">contact the academy ↗</a>.</p></div>'
 else:
  photos=list(dict.fromkeys(i['url'] for i in p['images']));count=len(photos)
  gallery=''.join(f'<button class="gallery-item" data-full="{asset(u)}" aria-label="Open {H(title)} photograph {i+1}"><img src="{asset(u,True)}" alt="{H(title)} — event photograph {i+1}" loading="lazy" decoding="async"></button>' for i,u in enumerate(photos))
  body=f'<div class="page-shell">{crumb(title,parent)}<section class="text-hero"><p class="eyebrow">ADLY CHESS / EVENT ARCHIVE</p><h1>{H(title)}</h1><p class="lead">The players, the games and the moments in between.</p></section>{img(photos[0],title,"gallery-cover",False) if photos else ""}<section class="gallery-section"><div class="section-heading"><h2>In the frame.</h2><span class="count">{count} photographs</span></div><div class="gallery-grid">{gallery}</div></section><p class="archive-note">This is a past-event photo gallery. <a href="/contact-us/">Ask about upcoming events ↗</a></p></div><dialog class="lightbox" id="gallery-dialog" aria-label="{H(title)} photo viewer"><button class="close" aria-label="Close photo viewer">✕</button><img alt=""><div class="lightbox-controls"><button data-prev aria-label="Previous photo">←</button><p data-counter aria-live="polite"></p><button data-next aria-label="Next photo">→</button></div></dialog>'
 write(path.strip('/'),title,'Explore '+title+' with Adly Chess Academy.',body,'events')
# Preserve the shop as its own route and reuse shared navigation.
p=D/'shop/index.html';text=p.read_text()
text=re.sub(r'<a href="#main" class="skip-link">.*?</a>', '', text)
text=re.sub(r'<div class="announcement">.*?</header>',header('shop'),text,flags=re.S)
text=re.sub(r'<footer(?: class="site-footer")?>.*?</footer>',footer(),text,flags=re.S)
text=text.replace('href="styles.css"','href="/styles.css"').replace('src="app.js"','src="/app.js"').replace('src="assets/','src="/assets/')
text=text.replace('src="/academy.js"', 'src="/academy.js?v=forms-1"')
p.write_text(text)
# Homepage: a cinematic opening within the established academy identity.
body=f'''<section class="home-hero" aria-labelledby="home-title"><img class="home-backdrop" src="/assets/home-ahmed-adly.webp" alt="Ahmed Adly studying a position at the chessboard" fetchpriority="high" width="1583" height="900"><div class="home-hero-inner"><p class="eyebrow">ADLY CHESS ACADEMY · EGYPT</p><h1 id="home-title">Find the champion<br><em>in you.</em></h1><p class="hero-description">A first move. A new way to think.<br>Discover chess with a community that helps every player take the next step.</p><div class="button-row"><a class="button" href="/{free}">Try a free class <span aria-hidden="true">↗</span></a><a class="quiet-link" href="/about-us/">Discover the academy</a></div></div><div class="hero-bottom"><span>Founded by Grandmaster Ahmed Adly</span><a class="hero-scroll" href="#your-game">Explore the academy <span aria-hidden="true">↓</span></a></div></section>
<div class="home-proof"><div><strong>A champion’s experience</strong><p>Founded by the 2007 World Junior Champion</p></div><div><strong>A personal path forward</strong><p>Coaching shaped around each player</p></div><div><strong>Wherever you play</strong><p>In-person and online classes</p></div></div>
<div class="page-shell"><section class="home-section" id="your-game"><div class="section-heading"><div><p class="eyebrow">EVERY PLAYER STARTS SOMEWHERE</p><h2>Your game.<br>Your next chapter.</h2></div><p>From learning the pieces to facing a new opponent, there’s always another move to discover.</p></div><div class="pathway-grid"><article class="pathway"><span class="pathway-number">01 / DISCOVER</span><h3>Start with curiosity.</h3><p>Learn the rules, explore the board and enjoy the challenge of your first games.</p><a href="/{free}">Try a first class ↗</a></article><article class="pathway"><span class="pathway-number">02 / DEVELOP</span><h3>Build your own game.</h3><p>Work with coaches on tactics, planning and the decisions that shape every position.</p><a href="/about-us/our-team/">Meet the coaches ↗</a></article><article class="pathway"><span class="pathway-number">03 / COMPETE</span><h3>Take your place.</h3><p>Experience the focus, sportsmanship and shared excitement of tournament chess.</p><a href="/events/tournaments/">Explore tournaments ↗</a></article></div></section></div>
<section class="home-story"><div class="page-shell home-section home-story-inner"><figure class="home-founder">{img(founder['image'],'Grandmaster Ahmed Adly, founder of the academy')}<figcaption class="founder-plate"><strong>GM Ahmed Adly</strong><span>Founder & CEO<br>World Junior Champion · 2007</span></figcaption></figure><div><p class="eyebrow">ONE CHAMPION. A SHARED AMBITION.</p><h2>Give the next generation<br>a stronger opening.</h2><div class="prose"><p>Ahmed Adly’s own journey inspired a simple ambition: give young players the coaching, structure and support he had worked so hard to find.</p><p>Today, that ambition brings students and coaches together around the board, with room to learn, compete and belong.</p></div><a class="button" href="/about-us/">Our story <span aria-hidden="true">↗</span></a></div></div></section>
<div class="page-shell"><section class="home-section home-events"><div class="section-heading"><div><p class="eyebrow">THE ADLY CHESS FAMILY</p><h2>Connected by the game.</h2></div><a href="/events/">All events ↗</a></div><div class="event-feature"><img src="/assets/home-community.webp" alt="Two chess players shake hands across the board before a game" loading="lazy" width="2000" height="841"><div class="event-feature-copy"><p class="eyebrow">ON THE BOARD. IN THE MOMENT.</p><h3>Good games.<br>Lasting connections.</h3><p>Step into the academy’s festivals, championships and tournament galleries. Meet a community that shares your love of chess.</p><a href="/events/">Explore the event archive ↗</a></div></div><div class="event-links"><a href="/events/adly-international-chess-festival/">Adly Chess Festival <span aria-hidden="true">↗</span></a><a href="/events/tournaments/">Tournaments <span aria-hidden="true">↗</span></a><a href="/events/sports-expo/">Sports Expo <span aria-hidden="true">↗</span></a></div></section>
<section class="home-section shop-teaser"><div><p class="eyebrow">THE ADLY COLLECTION</p><h2>For the next game.<br>And the one after.</h2><p>Boards, clocks and chess-inspired essentials. Bring a little more of the game into your everyday.</p><a class="button" href="/shop/">Explore the shop <span aria-hidden="true">↗</span></a></div><a class="shop-teaser-visual" href="/shop/" aria-label="Browse chess boards and the full Adly collection"><img src="/assets/wooden-board.jpg" alt="Wooden chess board from the Adly collection" loading="lazy" width="1200" height="1200"><div class="shop-teaser-caption"><span>Made for your next move</span><span aria-hidden="true">↗</span></div></a></section></div>
<section class="home-final"><p class="eyebrow">YOUR FIRST MOVE IS WAITING</p><h2>A new game.<br>A world of possibilities.</h2><p>Find the right starting point for your child.<br>Request a free trial class, in person or online.</p><a class="button" href="/{free}">Try a free class <span aria-hidden="true">↗</span></a></section>'''
write('','Home','Chess classes, coaching and a community for growing players. Discover Adly Chess Academy, founded by Grandmaster Ahmed Adly, and request a free trial class.',body,'home',False)
p=D/'index.html';s=p.read_text().replace('<title>Home | Adly Chess Academy</title>','<title>Adly Chess Academy | Find the Champion in You</title>').replace('<link rel="stylesheet" href="/academy.css">','<link rel="stylesheet" href="/academy.css"><link rel="stylesheet" href="/home.css">');p.write_text(s)
print('Created',len(list(D.rglob('index.html'))),'pages, including homepage and shop')

# Every page shares the same accessible scroll-reveal enhancement.
for page in D.rglob('index.html'):
 text=re.sub(r'<script src="/scroll-reveal\.js(?:\?[^"]*)?" defer></script>', '', page.read_text())
 text=text.replace('</head>', '<script src="/scroll-reveal.js?v=2" defer></script></head>')
 page.write_text(text)

# Shared cart and on-site checkout.
for page in D.rglob('index.html'):
 text=page.read_text()
 if '/cart.js' not in text:
  text=text.replace('</head>', '<link rel="stylesheet" href="/cart.css?v=1"><script src="/cart.js?v=1" defer></script></head>')
 page.write_text(text)
